Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

In [1]:
import numpy as np

In [3]:
l = [1,2,3,4]
l

[1, 2, 3, 4]

In [5]:
ar = np.array(l)
ar

array([1, 2, 3, 4])

In [6]:
type(ar)  # n dimensional array

numpy.ndarray

In [3]:
import numpy as np
np.array([[1,2],[2,3]])


array([[1, 2],
       [2, 3]])

In [9]:
l =np.array([[1,2,3],[4,5,6],[7,8,9]])
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.asarray(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.asanyarray(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
b = np.matrix(l)   # matrix is 2D
b

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
L2 = [1,2,5,6]
a = np.asanyarray(L2)
a

array([1, 2, 5, 6])

In [16]:
c = a
c

array([1, 2, 5, 6])

In [19]:
c[0] = 90
c

array([90,  2,  5,  6])

In [20]:
a[0] # changes in c are done in a     by reference # SWALLOW COPY

90

In [21]:
# DEEP COPY  - here no changes in previous variable
d = np.copy(a)

In [23]:
d[0] = 8

In [24]:
a[0]   

90

In [26]:
#fromfunction - it works on condition given
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
 iterable = (i*i for i in range(5))
iterable 

<generator object <genexpr> at 0x0000022D70DCA180>

In [32]:
np.fromiter( iterable , float)

array([ 0.,  1.,  4.,  9., 16.])

In [36]:
np.fromstring(' 234 234  ',sep = ' ')

array([234., 234.])

In [37]:
np.fromstring(' 234, 234 ,90,89  ',sep = ' ,')

array([234., 234.,  90.,  89.])

In [38]:
# datatypes  in Numpy 
l = [9,8,7,6]
ar = np.asarray(l)

In [39]:
ar

array([9, 8, 7, 6])

In [40]:
ar.ndim  # n dimensional  ndim 

1

In [41]:
l =np.array([[1,2,3],[4,5,6],[7,8,9]])
l.ndim

2

In [42]:
# arrar size - no. of element in array
l.size

9

In [43]:
ar.shape

(4,)

In [45]:
# datatype
ar.dtype

dtype('int32')

In [48]:
 ar29 = np.array([(1,7,8,9.8),(0.9,8,8,9)])
ar29

array([[1. , 7. , 8. , 9.8],
       [0.9, 8. , 8. , 9. ]])

In [52]:
ar29.dtype


dtype('float64')

In [53]:
ar29.size


8

In [54]:
ar29.shape

(2, 4)

In [55]:
# range function 
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [57]:
# it can take float  value
#list(range(9.9))    use arange function

In [58]:
np.arange(2.6,5,9)

array([2.6])

In [62]:
list(np.arange(2.6,4.5,.3))

[2.6,
 2.9,
 3.1999999999999997,
 3.4999999999999996,
 3.7999999999999994,
 4.1,
 4.399999999999999]

In [63]:
np.linspace(1,5,10)  # 10 data produces - 10 equal data 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [65]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
import numpy as np
np.zeros((2,3,3)) # 3D data 

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
 a = np.ones((2,3)) # matrix  with value 1
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
a+5

array([[6., 6., 6.],
       [6., 6., 6.]])

In [10]:
a*4

array([[4., 4., 4.],
       [4., 4., 4.]])

In [12]:
np.empty((3,4))

array([[1.01855798e-312, 1.08221785e-312, 1.01855798e-312,
        9.54898106e-313],
       [1.03977794e-312, 1.03977794e-312, 1.23075756e-312,
        1.10343781e-312],
       [1.10343781e-312, 9.76118064e-313, 1.14587773e-312,
        1.90979621e-312]])

In [13]:
# eye function - for identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.linspace(2,4,29)

array([2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429,
       2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714,
       2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ,
       3.07142857, 3.14285714, 3.21428571, 3.28571429, 3.35714286,
       3.42857143, 3.5       , 3.57142857, 3.64285714, 3.71428571,
       3.78571429, 3.85714286, 3.92857143, 4.        ])

In [16]:
# logspace
np.logspace(2,5,10) # it finds log values of linspace function with log base 10

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [17]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [22]:
# random data   it generates data as mean = 0,std =1 standarad normal distribution
arr = np.random.randn(1,2)   
arr

array([[0.79971593, 2.00597202]])

In [21]:
import pandas as pd
df = pd.DataFrame(arr)
df

0         1
0 -1.507369  0.735599

In [24]:
df.describe()

0         1
count  1.000000  1.000000
mean  -1.507369  0.735599
std         NaN       NaN
min   -1.507369  0.735599
25%   -1.507369  0.735599
50%   -1.507369  0.735599
75%   -1.507369  0.735599
max   -1.507369  0.735599

In [25]:
np.random.randint(1,110,(3,4)) # 3x4 matrix 

array([[99, 73, 87, 87],
       [42, 74, 90, 88],
       [14, 99, 18, 52]])

In [26]:
np.random.rand(3,4)

array([[0.20280798, 0.5488453 , 0.53189007, 0.41237007],
       [0.20678287, 0.99809272, 0.29974544, 0.9790855 ],
       [0.08043803, 0.42370971, 0.34152486, 0.868007  ]])

In [28]:
# make a dataframe of random values of 300x400
np.random.randint(1,110,(300,400))
pd.DataFrame(np.random.randint(1,110,(300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     71   63   22   29  108   94  103   64    1    8  ...   63   24    3   
1     72   22   90   17   23    1   88    9  107   19  ...  106   50  102   
2      4   67   57    7   71   57   54   11   75   35  ...   50   94   10   
3     56   30   64   16   95   14   70   93   60   38  ...   83    4   26   
4     47   72   50   20   68   83   10   42   82   74  ...   39  105   57   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   28   68   79   78   14   67    6   91   88   87  ...   12   67   83   
296   54    5   74  107   67   11   35  101   19   44  ...  106   26   15   
297   84   18   46   32   27   64   27   42   74   70  ...   95   88   86   
298   74   34   22    9   88   78  108   87   58   55  ...   19   16   35   
299   29   10    9   77   48   88  103   17  102    7  ...   12   68  103   

     393  394  395  396  397  398  399  
0     99   29   21  103   75   84   93  
1    101   36   30  109   89  101   45  
2    100   76   49   98   87  108   27  
3     41   84    1   79   86   21   11  
4      7  107   52   67   42   46   24  
..   ...  ...  ...  ...  ...  ...  ...  
295   43   36   33   96   13   66   41  
296   39   19  107   78    4   69   27  
297   30  109   98   14   95   28   28  
298    5    1   10   73   79   11   71  
299   38  109   52   91   96    4   75  

[300 rows x 400 columns]

In [31]:
 data = pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv("test.csv")
data
# store random data in csv file

In [33]:
arr = np.random.rand(3,4)
arr

array([[0.8213046 , 0.01957481, 0.91409121, 0.6089611 ],
       [0.8797892 , 0.92090926, 0.92640334, 0.25565143],
       [0.41797738, 0.07546659, 0.29971439, 0.19844363]])

In [35]:
arr.reshape(6,2)  # size of data = to reshape parameter
# arr.reshape(6,3)      xxxxxxxxxxxxxxxx

array([[0.8213046 , 0.01957481],
       [0.91409121, 0.6089611 ],
       [0.8797892 , 0.92090926],
       [0.92640334, 0.25565143],
       [0.41797738, 0.07546659],
       [0.29971439, 0.19844363]])

In [44]:
arr.reshape(6,2)

array([[0.8213046 , 0.01957481],
       [0.91409121, 0.6089611 ],
       [0.8797892 , 0.92090926],
       [0.92640334, 0.25565143],
       [0.41797738, 0.07546659],
       [0.29971439, 0.19844363]])

In [42]:
arr1 = arr.reshape(4,-133)
arr1

array([[0.8213046 , 0.01957481, 0.91409121],
       [0.6089611 , 0.8797892 , 0.92090926],
       [0.92640334, 0.25565143, 0.41797738],
       [0.07546659, 0.29971439, 0.19844363]])

In [45]:
arr1[1]

array([0.6089611 , 0.8797892 , 0.92090926])

In [46]:
arr1[1][1]  # indexing operation

0.8797892016299976

In [49]:
arr1[2:5 ,1]

array([0.25565143, 0.29971439])

In [56]:
 x = np.random.randint(1,100,(5,5))
x

array([[90, 70, 78, 11, 90],
       [92, 99, 43, 29, 95],
       [73, 12,  7, 60, 77],
       [61, 90,  3, 60, 55],
       [35, 53, 96, 64, 18]])

In [57]:
# data>50 
x>50

array([[ True,  True,  True, False,  True],
       [ True,  True, False, False,  True],
       [ True, False, False,  True,  True],
       [ True,  True, False,  True,  True],
       [False,  True,  True,  True, False]])

In [59]:
x

array([[90, 70, 78, 11, 90],
       [92, 99, 43, 29, 95],
       [73, 12,  7, 60, 77],
       [61, 90,  3, 60, 55],
       [35, 53, 96, 64, 18]])

In [61]:
x[2:4,[1,2]]

array([[12,  7],
       [90,  3]])

In [62]:
x[0][0]

90

In [68]:
array1 =np.random.randint(1,3,(3,3))


In [69]:
array1

array([[2, 2, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [74]:
array2 =np.random.randint(1,3,(3,3))
array2

array([[2, 1, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [75]:
# sum of two data   index to index mapping 
array1+array2

array([[4, 3, 4],
       [3, 3, 2],
       [3, 3, 3]])

In [76]:
array1-array2

array([[ 0,  1,  0],
       [-1, -1,  0],
       [ 1,  1,  1]])

In [77]:
array1*array2  # it is not matrix muliplication - it is index multiplication

array([[4, 2, 4],
       [2, 2, 1],
       [2, 2, 2]])

In [81]:
# matrix multiplication
array1@array2

array([[10,  8,  8],
       [ 5,  4,  4],
       [10,  8,  8]])

In [78]:
array1/array2

array([[1. , 2. , 1. ],
       [0.5, 0.5, 1. ],
       [2. , 2. , 2. ]])

In [82]:
arr1/0    # infinite

C:\Users\asus\AppData\Local\Temp\ipykernel_10524\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [83]:
array1+100

array([[102, 102, 102],
       [101, 101, 101],
       [102, 102, 102]])

In [84]:
array1**2

array([[4, 4, 4],
       [1, 1, 1],
       [4, 4, 4]])

# BROADCASTING

In [86]:
arr1 = np.zeros((4,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
row = np.array([1,2,3,4])
row

array([1, 2, 3, 4])

In [88]:
arr1 +row    # row wise broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [90]:
row.T   # NOT TRANSPOSED

array([1, 2, 3, 4])

In [94]:
# column wise broadcasting 
COL  = np.array([[1,2,3,4]])

In [92]:
COL.T

array([[1],
       [2],
       [3],
       [4]])

In [93]:
COL.T+ row

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [99]:
 y = np.random.randint(1,4,(3,4))
y

array([[3, 3, 3, 3],
       [3, 2, 1, 2],
       [1, 2, 1, 2]])

In [100]:
np.sqrt(y)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [1.73205081, 1.41421356, 1.        , 1.41421356],
       [1.        , 1.41421356, 1.        , 1.41421356]])

In [101]:
np.exp(y)

array([[20.08553692, 20.08553692, 20.08553692, 20.08553692],
       [20.08553692,  7.3890561 ,  2.71828183,  7.3890561 ],
       [ 2.71828183,  7.3890561 ,  2.71828183,  7.3890561 ]])

In [102]:
np.log10(y)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.47712125, 0.30103   , 0.        , 0.30103   ],
       [0.        , 0.30103   , 0.        , 0.30103   ]])