In [1]:
import pandas as pd
import numpy as np

In [4]:
array = np.random.randint(1,10,(2,3))


In [5]:
array

array([[2, 6, 4],
       [8, 2, 9]])

In [7]:
array.reshape(3,2)

array([[2, 6],
       [4, 8],
       [2, 9]])

#array.reshape(4,2)    #cannot reshape array of size 6 into shape (4,2)

In [9]:
array.reshape(2,-2333)

array([[2, 6, 4],
       [8, 2, 9]])

In [10]:
array.T

array([[2, 8],
       [6, 2],
       [4, 9]])

In [11]:
array

array([[2, 6, 4],
       [8, 2, 9]])

# Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [12]:
# flatten -- convert data into 1 D
array.flatten()

array([2, 6, 4, 8, 2, 9])

In [13]:
arr1 = np.array([1,3,4,5])

In [15]:
arr1

array([1, 3, 4, 5])

In [16]:
np.expand_dims(arr1 , axis = 1)  # changed dim to 2 by column

array([[1],
       [3],
       [4],
       [5]])

In [17]:
np.expand_dims(arr1 , axis = 0) 

array([[1, 3, 4, 5]])

In [20]:
np.squeeze(arr1)

array([1, 3, 4, 5])

In [21]:
data = np.array([[1],[2],[3]])

In [22]:
data

array([[1],
       [2],
       [3]])

In [23]:
np.squeeze(data)

array([1, 2, 3])

In [24]:
# repeat element  repeat( array_name ,value)
np.repeat(arr1 ,3)

array([1, 1, 1, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [29]:
arr1

array([1, 3, 4, 5])

In [28]:
# roll    it roll the array    roll(array_name , value)
np.roll(arr1,2)


array([4, 5, 1, 3])

In [30]:
# diag   put data in diagonal of matrix
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [31]:
# Binary OPeration 
arr2 = np.random.randint(1,10,(3,4))

In [32]:
arr2

array([[9, 5, 4, 3],
       [1, 6, 2, 4],
       [5, 3, 3, 9]])

In [33]:
arr3 = np.random.randint(1,10,(3,4))

In [34]:
arr3

array([[5, 9, 3, 6],
       [9, 3, 2, 4],
       [2, 7, 8, 1]])

In [35]:
arr2 + arr3

array([[14, 14,  7,  9],
       [10,  9,  4,  8],
       [ 7, 10, 11, 10]])

In [36]:
arr2 - arr3

array([[ 4, -4,  1, -3],
       [-8,  3,  0,  0],
       [ 3, -4, -5,  8]])

In [37]:
arr2 * arr3

array([[45, 45, 12, 18],
       [ 9, 18,  4, 16],
       [10, 21, 24,  9]])

In [38]:
arr2/arr3

array([[1.8       , 0.55555556, 1.33333333, 0.5       ],
       [0.11111111, 2.        , 1.        , 1.        ],
       [2.5       , 0.42857143, 0.375     , 9.        ]])

In [39]:
# remainder operation
arr2% arr3

array([[4, 5, 1, 3],
       [1, 0, 0, 0],
       [1, 3, 3, 0]])

In [40]:
# power
arr2** arr3

array([[  59049, 1953125,      64,     729],
       [      1,     216,       4,     256],
       [     25,    2187,    6561,       9]])

In [41]:
# and operations
arr2& arr3

array([[1, 1, 0, 2],
       [1, 2, 2, 4],
       [0, 3, 0, 1]])

In [42]:
arr2 | arr3

array([[13, 13,  7,  7],
       [ 9,  7,  2,  4],
       [ 7,  7, 11,  9]])

In [43]:
# negate operation 
-arr2

array([[-9, -5, -4, -3],
       [-1, -6, -2, -4],
       [-5, -3, -3, -9]])

In [44]:
arr2>arr3

array([[ True, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True]])

# String function

In [46]:
x = np.array(['pratima','jadon'])

In [47]:
x

array(['pratima', 'jadon'], dtype='<U7')

In [48]:
# upper
np.char.upper(x)

array(['PRATIMA', 'JADON'], dtype='<U7')

In [49]:
# title 
np.char.title(x)

array(['Pratima', 'Jadon'], dtype='<U7')

In [51]:
np.char.capitalize(x)

array(['Pratima', 'Jadon'], dtype='<U7')

In [52]:
# Mathematical  function
arr2

array([[9, 5, 4, 3],
       [1, 6, 2, 4],
       [5, 3, 3, 9]])

In [53]:
arr3

array([[5, 9, 3, 6],
       [9, 3, 2, 4],
       [2, 7, 8, 1]])

In [54]:
# sinosudal value
np.sin(arr2)

array([[ 0.41211849, -0.95892427, -0.7568025 ,  0.14112001],
       [ 0.84147098, -0.2794155 ,  0.90929743, -0.7568025 ],
       [-0.95892427,  0.14112001,  0.14112001,  0.41211849]])

In [55]:
np.cos(arr2)

array([[-0.91113026,  0.28366219, -0.65364362, -0.9899925 ],
       [ 0.54030231,  0.96017029, -0.41614684, -0.65364362],
       [ 0.28366219, -0.9899925 , -0.9899925 , -0.91113026]])

In [56]:
np.tan(arr2)

array([[-0.45231566, -3.38051501,  1.15782128, -0.14254654],
       [ 1.55740772, -0.29100619, -2.18503986,  1.15782128],
       [-3.38051501, -0.14254654, -0.14254654, -0.45231566]])

In [58]:
np.log10(arr2)

array([[0.95424251, 0.69897   , 0.60205999, 0.47712125],
       [0.        , 0.77815125, 0.30103   , 0.60205999],
       [0.69897   , 0.47712125, 0.47712125, 0.95424251]])

In [59]:
np.sqrt(arr2)

array([[3.        , 2.23606798, 2.        , 1.73205081],
       [1.        , 2.44948974, 1.41421356, 2.        ],
       [2.23606798, 1.73205081, 1.73205081, 3.        ]])

In [61]:
np.power(arr2,2)

array([[81, 25, 16,  9],
       [ 1, 36,  4, 16],
       [25,  9,  9, 81]], dtype=int32)

In [62]:
np.mean(arr2)

4.5

In [64]:
np.median(arr2)

4.0

In [65]:
np.std(arr2)

2.3979157616563596

In [66]:
np.var(arr2)

5.75

In [67]:
np.min(arr2)

1

In [68]:
np.max(arr2)

9

Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

# The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



In [69]:
# copy 
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [71]:
# view
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.
concatenate() function

In [72]:
np.concatenate((arr3, arr2))

array([[5, 9, 3, 6],
       [9, 3, 2, 4],
       [2, 7, 8, 1],
       [9, 5, 4, 3],
       [1, 6, 2, 4],
       [5, 3, 3, 9]])

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [75]:
np.stack((arr3 ,arr2 ),axis =1)

array([[[5, 9, 3, 6],
        [9, 5, 4, 3]],

       [[9, 3, 2, 4],
        [1, 6, 2, 4]],

       [[2, 7, 8, 1],
        [5, 3, 3, 9]]])

# Stacking Along Rows


NumPy provides a helper function: hstack() to stack along rows.



# Stacking Along Columns


NumPy provides a helper function: vstack()  to stack along columns.


# Stacking Along Height (depth)


NumPy provides a helper function: dstack() to stack along height, which is the same as depth



#  Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [76]:
np.array_split(arr2, 3)

[array([[9, 5, 4, 3]]), array([[1, 6, 2, 4]]), array([[5, 3, 3, 9]])]

In [77]:
arr2

array([[9, 5, 4, 3],
       [1, 6, 2, 4],
       [5, 3, 3, 9]])

In [78]:
np.array_split(arr2, 2)

[array([[9, 5, 4, 3],
        [1, 6, 2, 4]]),
 array([[5, 3, 3, 9]])]

# Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [83]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

np.where(arr == 4)
# Which means that the value 4 is present at index 3, 5, and 6.


(array([3, 5, 6], dtype=int64),)

searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays.

In [85]:
np.searchsorted(arr, 7)

7

Search From the Right Side
By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [87]:
np.searchsorted(arr ,5 ,side = 'right')

7

In [89]:
# The NumPy ndarray object has a function called sort(), that will sort a specified array.

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


Getting some elements out of an existing array and creating a new array out of them is called filtering.