In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,10,(3,3))

array([[5, 8, 5],
       [7, 2, 7],
       [5, 5, 6]])

In [3]:
# sort ,search and counting function
arr = np.array([4,3,6,7,8])

In [4]:
arr

array([4, 3, 6, 7, 8])

In [7]:
arr.sort()

In [8]:
np.sort(arr)

array([3, 4, 6, 7, 8])

In [13]:
# SEARCHSORTED
np.searchsorted(arr,3)

0

In [14]:
arr1 = np.array([0,12,22,44,5,6,7])
# count non zero data
np.count_nonzero(arr1)

6

In [15]:
np.where(arr1>3)   # at indexes 

(array([1, 2, 3, 4, 5, 6], dtype=int64),)

In [16]:
np.extract(arr1 >12 ,arr1)   # extract data based on condition

array([22, 44])

In [17]:
# Numpy - Byte swapping
arr.byteswap()

array([ 50331648,  67108864, 100663296, 117440512, 134217728])

In [18]:
# copy vs view 
a = np.copy(arr1)

In [19]:
a

array([ 0, 12, 22, 44,  5,  6,  7])

In [23]:
a[1] = 3

In [25]:
a

array([ 0,  3, 22, 44,  5,  6,  7])

In [24]:
arr1[1]

12

In [26]:
# changes in a affect arr1[]  in copy 

In [27]:
b = np.copy(arr1)

In [28]:
b[0]=2

In [29]:
b

array([ 2, 12, 22, 44,  5,  6,  7])

In [31]:
arr1[0]   # no change in case of view

0

# Numpy - Matrix Library

In [32]:
import numpy.matlib as nm

In [34]:
nm.zeros((3,3))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [35]:
nm.ones((4,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
nm.eye(5)  # identity matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Linear Algebra

In [40]:
arr1 = np.random.randint([[2,3],[4,5]])

In [41]:
arr1

array([[0, 1],
       [0, 1]])

In [42]:
arr2 = np.random.randint([[2,3],[4,5]])

In [43]:
arr2

array([[1, 2],
       [3, 1]])

In [44]:
# dot product 
np.dot(arr1,arr2)

array([[3, 1],
       [3, 1]])

In [45]:
# matrix multiplication
arr1@arr2

array([[3, 1],
       [3, 1]])